name: WakaTime

on:
  schedule:
    - cron: '0 0/12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update the README w/ WakaTime data
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
